spring:
  cloud:
    stream:
      bindings:
        outputChannel:
          destination: book-stream
        otpChannel:
          destination: otp-book-stream
  rabbitmq:
    host: 192.168.0.141
    port: 5672
    username: guest
    password: guest